[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path = "forge-cache"
optimizer = true
optimizer_runs = 20000
solc = "0.8.26"
evm_version = "cancun"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# Skip OZ test/fv files — they have extra deps we don't need.
skip = [
    "lib/openzeppelin-contracts/test/**",
    "lib/openzeppelin-contracts/fv/**",
    "lib/create3-deployer/**",
]
