import {
  pgTable,
  text,
  timestamp,
  integer,
} from "drizzle-orm/pg-core";

// ── Users ───────────────────────────────────────────────────────

export const users = pgTable("users", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  privyId: text("privy_id").unique(), // Privy DID — primary auth identifier
  name: text("name"),
  email: text("email").unique(),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  // Per-user smart contract addresses (deployed on first login via smart wallet)
  agentRegistryAddress: text("agent_registry_address"),
  conditionAddress: text("condition_address"),
  // API key for agent connections — only the SHA-256 hash is stored
  apiKey: text("api_key").unique(),
  // Rate limit settings (requests per window, configurable by user)
  rateLimitPerMinute: integer("rate_limit_per_minute").default(60).notNull(),
  rateLimitPerHour: integer("rate_limit_per_hour").default(1000).notNull(),
  rateLimitPerDay: integer("rate_limit_per_day").default(10000).notNull(),
});

// ── Whitelisted agents ───────────────────────────────────────────

export const agents = pgTable("agents", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  agentKey: text("agent_key").notNull().unique(), // plaintext — viewable any time
  allowedSecrets: text("allowed_secrets").array().notNull().default([]),       // display names
  allowedSecretIds: text("allowed_secret_ids").array().notNull().default([]),  // bytes32 0x-hex for grantAccess
  policy: text("policy").notNull().default(""),
  status: text("status").notNull().default("active"), // "active" | "inactive"
  walletAddress: text("wallet_address"),  // agent's Ethereum wallet — used to call CDR
  ipId: text("ip_id"),                   // Story Protocol IP Asset address
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  // Per-agent call rate limits (all optional; null = no limit)
  rateLimitEnabled: boolean("rate_limit_enabled").notNull().default(false),
  rateLimitMaxTotal: integer("rate_limit_max_total"),   // max successful calls ever
  rateLimitPerMinute: integer("rate_limit_per_minute"),
  rateLimitPerHour: integer("rate_limit_per_hour"),
  rateLimitPerDay: integer("rate_limit_per_day"),
});

// ── Secrets ──────────────────────────────────────────────────────
// Each row is one secret. secretId is a client-generated bytes32 (stored as
// 0x-prefixed hex) baked into the CDR vault's readConditionData at allocation,
// so KeyringAccessCondition can identify the vault without needing the CDR uuid.

export const secrets = pgTable("secrets", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  // bytes32 secretId as 0x-prefixed hex — baked into CDR readConditionData
  secretId: text("secret_id").notNull().unique(),
  // CDR-assigned vault number — needed by agents to call cdr.read(uuid, ...)
  cdrVaultUuid: integer("cdr_vault_uuid").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
});

// ── API call log ─────────────────────────────────────────────────
// One row per request that passes authentication at /api/[apiKey].

export const apiCalls = pgTable("api_calls", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  agentId: text("agent_id")
    .references(() => agents.id, { onDelete: "set null" }), // null for GET/unauthenticated
  path: text("path").notNull().default(""),
  method: text("method").notNull().default("GET"),
  status: integer("status").notNull().default(200),
  latencyMs: integer("latency_ms"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
});

// ── Types ───────────────────────────────────────────────────────

export type User = typeof users.$inferSelect;
export type ApiCall = typeof apiCalls.$inferSelect;
export type Agent = typeof agents.$inferSelect;
export type Secret = typeof secrets.$inferSelect;
