// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import { ICDRReadCondition } from "./interfaces/ICDRReadCondition.sol";
import { IAgentRegistry }    from "./interfaces/IAgentRegistry.sol";
import { IERC165 }            from "@openzeppelin/contracts/utils/introspection/IERC165.sol";

/// @title  KeyringAccessCondition
/// @notice CDR read-condition contract for Keyring. The CDR precompile calls
///         checkReadCondition() before releasing partial-decryption shares.
///
/// Per-vault identity: each CDR vault is allocated with
///   readConditionData = abi.encode(bytes32 secretId)
/// where `secretId` is generated by the dashboard before calling CDR.allocate().
///
/// Unlock conditions (all must pass):
///   1. caller's wallet is registered as an active IP Asset in AgentRegistry
///   2. that IP Asset has an active grant for `secretId`
///   3. the grant hasn't expired  (0 = permanent)
contract KeyringAccessCondition is ICDRReadCondition, IERC165 {
    // ──────────────────────────────────────────────────────── state ──

    IAgentRegistry public immutable REGISTRY;

    /// secretId → vault owner (set after CDR vault is allocated)
    mapping(bytes32 secretId => address) public vaultOwner;

    /// secretId → ipId → active
    mapping(bytes32 secretId => mapping(address ipId => bool)) public grantActive;

    /// secretId → ipId → expiry (unix ts; 0 = permanent)
    mapping(bytes32 secretId => mapping(address ipId => uint256)) public grantExpiry;

    // ──────────────────────────────────────────────────────── events ──

    event VaultRegistered(bytes32 indexed secretId, address indexed owner);
    event AccessGranted(bytes32 indexed secretId, address indexed ipId, uint256 expiresAt);
    event AccessRevoked(bytes32 indexed secretId, address indexed ipId);

    // ──────────────────────────────────────────────────────── errors ──

    error NotVaultOwner(bytes32 secretId);
    error VaultNotRegistered(bytes32 secretId);
    error ZeroAddress();

    // ──────────────────────────────────────────────────────── constructor ──

    constructor(address agentRegistry_) {
        if (agentRegistry_ == address(0)) revert ZeroAddress();
        REGISTRY = IAgentRegistry(agentRegistry_);
    }

    // ──────────────────────────────────────────────── external write ──

    /// @notice Called by the dashboard after allocating a CDR vault.
    ///         Records msg.sender as the vault owner so they can manage grants.
    function registerVault(bytes32 secretId) external {
        address existing = vaultOwner[secretId];
        if (existing != address(0) && existing != msg.sender) revert NotVaultOwner(secretId);
        vaultOwner[secretId] = msg.sender;
        emit VaultRegistered(secretId, msg.sender);
    }

    /// @notice Grants an agent IP Asset read access to a secret vault.
    /// @param secretId  The Keyring-internal secret identifier.
    /// @param ipId      The agent's Story Protocol IP Asset address.
    /// @param expiresAt Unix timestamp after which access lapses (0 = permanent).
    function grantAccess(bytes32 secretId, address ipId, uint256 expiresAt) external {
        _onlyVaultOwner(secretId);
        if (ipId == address(0)) revert ZeroAddress();
        grantActive[secretId][ipId]  = true;
        grantExpiry[secretId][ipId]  = expiresAt;
        emit AccessGranted(secretId, ipId, expiresAt);
    }

    /// @notice Revokes an agent's access to a secret vault immediately.
    function revokeAccess(bytes32 secretId, address ipId) external {
        _onlyVaultOwner(secretId);
        grantActive[secretId][ipId] = false;
        emit AccessRevoked(secretId, ipId);
    }

    // ────────────────────────────────── IERC165 ──

    /// @notice ERC-165 interface detection.
    /// @dev    ICDRReadCondition interfaceId = bytes4(keccak256("checkReadCondition(uint32,bytes,bytes,address)"))
    ///         = 0x8db3eb17
    function supportsInterface(bytes4 interfaceId) external pure override returns (bool) {
        return interfaceId == type(IERC165).interfaceId          // 0x01ffc9a7
            || interfaceId == type(ICDRReadCondition).interfaceId; // 0x8db3eb17
    }

    // ────────────────────────────────── ICDRReadCondition ──

    /// @notice Called by the CDR precompile.
    /// conditionData = abi.encode(bytes32 secretId) baked in at allocation time.
    /// caller = agent's wallet address making the CDR read request.
    function checkReadCondition(
        uint32  /* uuid */,
        bytes calldata /* accessAuxData */,
        bytes calldata conditionData,
        address caller
    ) external view override returns (bool) {
        // Decode the secretId baked in at allocation time
        if (conditionData.length < 32) return false;
        bytes32 secretId = abi.decode(conditionData, (bytes32));

        // Condition 1: caller maps to a registered, active IP Asset
        address ipId = REGISTRY.getIpId(caller);
        if (ipId == address(0))            return false;
        if (!REGISTRY.isActiveAgent(ipId)) return false;

        // Condition 2: IP Asset has an active grant for this secret
        if (!grantActive[secretId][ipId])  return false;

        // Condition 3: grant hasn't expired
        uint256 exp = grantExpiry[secretId][ipId];
        if (exp != 0 && block.timestamp >= exp) return false;

        return true;
    }

    // ──────────────────────────────────────────────────────── internal ──

    function _onlyVaultOwner(bytes32 secretId) internal view {
        if (vaultOwner[secretId] == address(0)) revert VaultNotRegistered(secretId);
        if (vaultOwner[secretId] != msg.sender)  revert NotVaultOwner(secretId);
    }
}
